#! /bin/csh -f

set name="ft_ls"

touch Makefile && chmod 755 Makefile

echo '#\!/usr/bin/make -f'  >> Makefile
echo "" >> Makefile
echo "NAME = $name" >> Makefile
echo "" >> Makefile
echo 'CFLAGS = -Wall -Wextra -Werror -g' >> Makefile
echo "" >> Makefile
echo 'SRCS =	main' >> Makefile
echo "" >> Makefile
echo 'SRC_DIR = ./sources/' >> Makefile
echo 'OBJ_DIR = ./obj/' >> Makefile
echo 'INC_DIR = ./includes/' >> Makefile
echo 'LIBFT_DIR = ./libft/' >> Makefile
echo "" >> Makefile
echo 'SRC = $(addprefix $(SRC_DIR), $(SRC_FILES))' >> Makefile
echo 'OBJ = $(addprefix $(OBJ_DIR), $(OBJ_FILES))' >> Makefile
echo 'LIBFT = $(addprefix $(LIBFT_DIR), libft.a)' >> Makefile
echo 'OBJ_FILES = $(SRCS:%=%.o)' >> Makefile
echo 'SRC_FILES = $(SRCS:%=%.c)' >> Makefile
echo "" >> Makefile
echo "" >> Makefile
echo 'all: obj $(LIBFT) $(NAME)' >> Makefile
echo "" >> Makefile
echo 'obj:' >> Makefile
echo '	mkdir -p $(OBJ_DIR)' >> Makefile
echo "" >> Makefile
echo '$(OBJ_DIR)%.o:$(SRC_DIR)%.c' >> Makefile
echo '	gcc -g -Wall -Werror -Wextra -c -I ./libft/libft.h -I includes  -o $@ -c $<' >> Makefile
echo "" >> Makefile
echo '$(LIBFT):' >> Makefile
echo '	make -C $(LIBFT_DIR)' >> Makefile
echo "" >> Makefile
echo '$(NAME): $(OBJ)' >> Makefile
echo '	gcc -g -shared -ldl $(LIBFT) $(OBJ) -o $(NAME)' >> Makefile
echo "" >> Makefile
echo 'clean:' >> Makefile
echo '	rm -rf $(OBJ_DIR)' >> Makefile
echo '	make -C $(LIBFT_DIR) clean' >> Makefile
echo "" >> Makefile
echo 'fclean: clean' >> Makefile
echo '	rm -f $(NAME)' >> Makefile
echo '	make -C $(LIBFT_DIR) fclean' >> Makefile
echo "" >> Makefile
echo 're: fclean all' >> Makefile
echo "" >> Makefile
echo '.PHONY: clean fclean all re' >> Makefile


